name: star-tracker
channels:
  - defaults
dependencies:
  - black=19.10b0  # Dev
  - flake8=4.0.1  # Dev
  - isort=5.9.3  # Dev
  - numpy=1.22.3
  - pandas=1.4.2
  - pip=21.2.4
  - pylint=2.12.2
  - python=3.10.4
  - pip:
    - requests==2.28.0
    - streamlit==1.10.0
